defaultContentLanguage = 'en'
pluralizeListTitles = false

[languages]
  [languages.en]
    title = 'DevmentorLive'
    weight = 1
[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0 "
    max = "0.111.3"
